# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyTubeSubscription (6fff56f5-221e-4a40-a5a1-075069992b7d)'
    appType: 'webAppLinux'
    appName: 'streambeacon-api'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|7.0'

- task: CmdLine@2
  inputs:
    script: dir $(Build.ArtifactStagingDirectory) /s
